# Generated by Django 3.2.8 on 2021-11-02 02:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0002_tooth'),
    ]

    operations = [
        migrations.RenameField(
            model_name='anamnese',
            old_name='alergia',
            new_name='allergy',
        ),
        migrations.RenameField(
            model_name='anamnese',
            old_name='hemorragia',
            new_name='bleeding',
        ),
        migrations.RenameField(
            model_name='anamnese',
            old_name='medicamento',
            new_name='medicine',
        ),
        migrations.RenameField(
            model_name='anamnese',
            old_name='gestante',
            new_name='pregnant',
        ),
        migrations.RenameField(
            model_name='anamnese',
            old_name='pressao',
            new_name='pressure',
        ),
        migrations.RenameField(
            model_name='anamnese',
            old_name='doenca_sistemica',
            new_name='systemic_disease',
        ),
    ]
