# Generated by Django 3.2.8 on 2021-11-01 23:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('form', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=200)),
                ('number', models.IntegerField()),
                ('complement', models.CharField(max_length=200)),
                ('district', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, verbose_name='Nome completo')),
                ('cpf', models.CharField(max_length=11, verbose_name='CPF')),
                ('rg', models.CharField(max_length=7, verbose_name='RG')),
                ('birth_date', models.DateTimeField(verbose_name='Data de nascimento')),
                ('anamnese', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='form.anamnese')),
                ('endereco', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='perfil.endereco')),
            ],
        ),
    ]
