# Generated by Django 3.2.8 on 2021-11-02 01:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0002_tooth'),
        ('perfil', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='anamnese',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='form.anamnese'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='endereco',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='perfil.endereco'),
        ),
    ]
